### ISSUE TITLE
Negative readings?

### ISSUE THREAD

**Issue by beicnet** [adafruit/Adafruit_SHT31#12]
Hi there,

I'm trying to read outdoor values, but something is wrong, I'm getting wrong readings.

SHT3x readings:
```
Temperature: 3.59c
Humidity: 68.50%
```
But, the real values should be:
```
Temperature: -0.90c
Humidity: 96.00 %
```
So, can you tell me what is wrong here?

Already tryied a second sensor, but got same reagings.

Using: Arduino IDE v1.8.2, ESP8266 Core v2.3.0 with WeMos D1 mini board.

Kind Regards,
Viktor

**Comment by hoffmannjan** [comment]
Tested with some fresh ice - got even -11*C and It all was valid. Please reopen if problem persist. Thanks!
