### ISSUE TITLE
Reduce delay before reading data

### ISSUE THREAD

**Issue by phckopper** [adafruit/Adafruit_SHT31#13]
Hello,
The following delay shouldn't me smaller? 500ms is probably overkill, as the datasheet specifies the maximum measuring time for the high repeatability as 15ms.

https://github.com/adafruit/Adafruit_SHT31/blob/5576352d93fe5728a3f0bd861bbbb2d0bc2fccba/Adafruit_SHT31.cpp#L73

I suggest changing it to 20ms as it would still provide a margin and would be much faster.

Thanks

**Comment by microbuilder** [comment]
Fixed in the latest update!

**Comment by olikraus** [comment]
I just came across the same problem. Unfortunately the release is not yet available in Arduino IDE.
Please update library.properties and create a new release for this repo. Thanks!
