### ISSUE TITLE
Adafruit_SHT31::begin always returns true

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_SHT31#2]
This line is commented out:
//return (readStatus() == 0x40);

Testing for presence is useful during setup. Even when the board is not present and/or not fully operational, readTemperature will return 0.0 & readHumidity will return 0.0. Temperature of 0.0 is perfectly valid, though humidity of 0.0 is quite unlikely.

**Comment by anecdata** [comment]
It appears that the status after reset should be 0x8010: bit 15 indicates an alert status is pending (including various levels of reset), and bit 4 indicates reset detected. 

Some discussion of SHT31 presence testing at:
[http://forums.adafruit.com/viewtopic.php?f=22&t=87407](http://forums.adafruit.com/viewtopic.php?f=22&t=87407)

**Comment by anecdata** [comment]
Seeing an 0x8050 status in the wild now, which is unusual since a reserved bit is now set.

**Comment by anecdata** [comment]
Suggestion to use serial number as a startup success test:
[https://forums.adafruit.com/viewtopic.php?f=22&t=87407#p450345](https://forums.adafruit.com/viewtopic.php?f=22&t=87407#p450345)

Which seems consistent with Sensiron's sample code:
[https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/Sample_Codes_Software/Humidity_and_Temperature_Sensors/Sensirion_Humidity_and_Temperature_Sensors_SHT3x_Sample_Code_V2.pdf](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/Sample_Codes_Software/Humidity_and_Temperature_Sensors/Sensirion_Humidity_and_Temperature_Sensors_SHT3x_Sample_Code_V2.pdf)

**Comment by acekrystal** [comment]
I changed the original "sht31.begin" to return correct true or false using the already existing "sht31.readStatus" function.

I basically tested what code "sht31.readStatus" returns in decimals when sensor is not connected, and used that for a simple if statement.

in Adafruit_SHT31.cpp new "begin" function changes:
```
boolean Adafruit_SHT31::begin(uint8_t i2caddr) {
  Wire.begin();
  _i2caddr = i2caddr;
  reset();
  //return (readStatus() == 0x40);
+  if (readStatus() != 65535){ // None connected sensors seem to return decimal 65535.
+	  return true;
+  }else{
+	  return false;
+  }
-  return true;

}
```

**Comment by hoffmannjan** [comment]
Added in #19, thanks @acekrystal ! 👍
