### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by matthijskooijman** [adafruit/Adafruit_SHT31#23]
This library says it is licensed under the "BSD" license, but that has multiple variations. I cannot find the actual license text in the repository either, so this makes it ambiguous what license is used exactly. Could you clarify, e.g. by including the full license text in the source files or in a `LICENSE` file and referring to that?

Also, the example does not state any license at all in the source file itself, which would be more explicit if it did.

**Comment by ladyada** [comment]
added

**Comment by matthijskooijman** [comment]
Thanks!
