### ISSUE TITLE
minus temperatures

### ISSUE THREAD

**Issue by Smerk80** [adafruit/Adafruit_SHT31#24]
Hello, since version 1.1.4, negative temperatures are displayed incorrectly. When I run the sht31test sketch I get the following output at negative temperatures Temp * C = 42949648.00

**Comment by ladyada** [comment]
@dirkmueller hi please fix the above - we will revert your commit if we dont hear from you in a few days. thanks!

**Comment by Smerk80** [comment]
Thank you its working

**Comment by caternuson** [comment]
Fix should be available via the 1.1.6 release:
https://github.com/adafruit/Adafruit_SHT31/releases/tag/1.1.6
